---
- name: My Playbook for Variables Lesson
  hosts: all
  become: yes

  vars:
    messagel: Privet
    message2: World
    secret : XCVBXHXIJOIJOIJOIDJOIDJODJ

  tasks: 
  - name: Print Secret variable
    debug:
      var: secret

  - debug:
      msg: "Sekretnoe slovo: {{ secret }}"

  - debug: 
      msg: "Vladelec Etogo Servera -->{{ owner }1<--"
  
  - set_fact: full_message="{{ messagel }} {{ message2 }} from {{ owner }}"
  
  - debug: 
      var: full_message 
      
  - debug: 
      var: ansible_distribution
      
  - shell: uptime
    register: results

  - debug:
      var: results.stdout 
...