---
- name: Install Apache web server
  hosts: all
  become: yes
  
  tasks:
  - name: Install Apache
    apt: name=httpd state=latest
  
  - name: Start and Enable Apache
    service: state=started enabled=yes
...